In [1]:
import pandas as pd
from nba_api.stats.static import players, teams
from nba_api.stats.endpoints import playergamelog, playbyplay, playbyplayv2, alltimeleadersgrids
from nba_api.stats.endpoints import FranchiseLeaders, CommonPlayerInfo

In [2]:
# Define the player ID
deni = players.get_players()
All_Players = pd.DataFrame(deni)
All_Players

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False
...       ...                  ...        ...           ...        ...
4826  1627790           Ante Zizic       Ante         Zizic      False
4827    78647             Jim Zoet        Jim          Zoet      False
4828    78648            Bill Zopf       Bill          Zopf      False
4829  1627826          Ivica Zubac      Ivica         Zubac       True
4830    78650           Matt Zunic       Matt         Zunic      False

[4831 rows x 5 columns]

In [3]:
# Search for players that match the name "Deni Avdija" and Get the first player in the search results
deni = players.find_players_by_full_name("leBron james")[0]
deni

{'id': 2544,
 'full_name': 'LeBron James',
 'first_name': 'LeBron',
 'last_name': 'James',
 'is_active': True}

In [4]:
# Extract the player's ID
deni_id = deni["id"]

# Get the player's game log
gamelog = playergamelog.PlayerGameLog(player_id=deni_id)

# Create a DataFrame from the player's game log
df_deni_games = gamelog.get_data_frames()[0]

pd.set_option('display.max_columns', None)
df_deni_games

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22022,2544,0022200821,"FEB 07, 2023",LAL vs. OKC,L,34,13,20,0.650,4,6,0.667,8,10,0.800,0,7,7,3,3,0,4,3,38,8,1
1,22022,2544,0022200798,"FEB 04, 2023",LAL @ NOP,L,40,10,22,0.455,1,7,0.143,6,9,0.667,0,9,9,6,0,0,2,2,27,-5,1
2,22022,2544,0022200778,"FEB 02, 2023",LAL @ IND,W,33,11,19,0.579,2,5,0.400,2,2,1.000,2,5,7,7,0,0,3,1,26,-4,1
3,22022,2544,0022200765,"JAN 31, 2023",LAL @ NYK,W,43,11,25,0.440,2,8,0.250,4,7,0.571,1,9,10,11,1,0,5,2,28,22,1
4,22022,2544,0022200749,"JAN 28, 2023",LAL @ BOS,L,44,15,30,0.500,6,12,0.500,5,6,0.833,1,8,9,8,0,0,2,2,41,2,1
5,22022,2544,0022200729,"JAN 25, 2023",LAL vs. SAS,W,35,8,20,0.400,1,6,0.167,3,4,0.750,1,8,9,11,0,0,6,0,20,2,1
6,22022,2544,0022200719,"JAN 24, 2023",LAL vs. LAC,L,33,16,29,0.552,9,14,0.643,5,5,1.000,1,7,8,7,2,1,0,0,46,-14,1
7,22022,2544,0022200705,"JAN 22, 2023",LAL @ POR,W,36,14,24,0.583,2,7,0.286,7,10,0.700,0,11,11,4,0,2,4,2,37,17,1
8,22022,2544,0022200690,"JAN 20, 2023",LAL vs. MEM,W,37,8,21,0.381,1,5,0.200,6,7,0.857,2,7,9,6,2,2,3,4,23,9,1
9,22022,2544,0022200677,"JAN 18, 2023",LAL vs. SAC,L,37,11,25,0.440,2,9,0.222,8,9,0.889,0,8,8,9,1,1,1,0,32,-16,1
10,22022,2544,0022200664,"JAN 16, 2023",LAL vs. HOU,W,36,16,26,0.615,5,10,0.500,11,12,0.917,1,7,8,9,0,0,0,1,48,19,1
11,22022,2544,0022200655,"JAN 15, 2023",LAL vs. PHI,L,35,15,23,0.652,1,5,0.200,4,5,0.800,0,8,8,10,1,1,3,1,35,19,1
12,22022,2544,0022200630,"JAN 12, 2023",LAL vs. DAL,L,47,9,28,0.321,0,7,0.000,6,10,0.600,6,10,16,9,2,0,3,0,24,-3,1
13,22022,2544,0022200595,"JAN 07, 2023",LAL @ SAC,W,38,14,28,0.500,1,6,0.167,8,9,0.889,1,7,8,7,1,0,4,2,37,15,1
14,22022,2544,0022200590,"JAN 06, 2023",LAL vs. ATL,W,33,10,19,0.526,1,5,0.200,4,6,0.667,0,7,7,10,0,0,5,0,25,12,1
15,22022,2544,0022200551,"JAN 02, 2023",LAL @ CHA,W,40,16,26,0.615,0,5,0.000,11,15,0.733,0,11,11,6,1,0,3,1,43,9,1
16,22022,2544,0022200530,"DEC 30, 2022",LAL @ ATL,W,40,18,27,0.667,4,6,0.667,7,9,0.778,2,8,10,9,0,1,5,0,47,12,1
17,22022,2544,0022200518,"DEC 28, 2022",LAL @ MIA,L,33,10,18,0.556,2,5,0.400,5,5,1.000,0,9,9,6,0,0,6,4,27,-4,1
18,22022,2544,0022200505,"DEC 27, 2022",LAL @ ORL,W,31,12,24,0.500,0,7,0.000,4,5,0.800,2,5,7,5,1,1,4,1,28,8,1
19,22022,2544,0022200494,"DEC 25, 2022",LAL @ DAL,L,34,13,23,0.565,0,4,0.000,12,12,1.000,0,6,6,5,0,0,2,2,38,2,1
20,22022,2544,0022200492,"DEC 23, 2022",LAL vs. CHA,L,34,15,23,0.652,4,8,0.500,0,2,0.000,0,2,2,8,1,0,3,2,34,-6,1
21,22022,2544,0022200475,"DEC 21, 2022",LAL @ SAC,L,34,11,21,0.524,0,4,0.000,9,10,0.900,0,6,6,11,0,2,2,0,31,-4,1
22,22022,2544,0022200451,"DEC 18, 2022",LAL vs. WAS,W,37,13,24,0.542,1,4,0.250,6,8,0.750,1,6,7,9,0,1,0,0,33,10,1
23,22022,2544,0022200437,"DEC 16, 2022",LAL vs. DEN,W,36,13,21,0.619,1,4,0.250,3,4,0.750,1,8,9,4,2,0,2,2,30,26,1
24,22022,2544,0022200413,"DEC 13, 2022",LAL vs. BOS,L,43,14,25,0.560,3,11,0.273,2,4,0.500,0,9,9,9,2,1,4,4,33,10,1
25,22022,2544,0022200396,"DEC 11, 2022",LAL @ DET,W,37,14,24,0.583,2,6,0.333,5,5,1.000,1,4,5,5,1,0,1,1,35,18,1
26,22022,2544,0022200382,"DEC 09, 2022",LAL @ PHI,L,44,9,22,0.409,1,8,0.125,4,8,0.500,1,3,4,6,2,0,3,3,23,-10,1
27,22022,2544,0022200360,"DEC 06, 2022",LAL @ CLE,L,36,8,17,0.471,2,6,0.333,3,4,0.750,4,13,17,4,1,1,3,0,21,-14,1
28,22022,2544,0022200349,"DEC 04, 2022",LAL @ WAS,W,34,12,26,0.462,2,7,0.286,3,4,0.750,1,7,8,6,1,0,5,3,29,13,1
29,22022,2544,0022200331,"DEC 02, 2022",LAL @ MIL,W,37,12,27,0.444,3,6,0.500,1,2,0.500,1,7,8,11,2,0,0,2,28,6,1
30,22022,2544,0022200324,"NOV 30, 2022",LAL vs. POR,W,33,12,18,0.667,6,8,0.750,1,3,0.333,2,5,7,8,0,1,2,1,31,8,1
31,22022,2544,0022200308,"NOV 28, 2022",LAL vs. IND,L,36,8,22,0.364,3,10,0.300,2,3,0.667,1,6,7,3,1,0,1,1,21,-7,1
32,22022,2544,0022200288,"NOV 26, 2022",LAL @ SAS,W,35,11,21,0.524,7,12,0.583,10,10,1.000,0,11,11,3,1,1,4,3,39,-3,1
33,22022,2544,0022200282,"NOV 25, 2022",LAL @ SAS,W,33,8,17,0.471,1,4,0.250,4,4,1.000,0,8,8,5,3,1,9,2,21,16,1
34,22022,2544,0022200170,"NOV 09, 2022",LAL @ LAC,L,32,12,22,0.545,4,9,0.444,2,4,0.500,1,7,8,5,2,0,3,2,30,-17,1
35,22022,2544,0022200140,"NOV 06, 2022",LAL vs. CLE,L,34,13,23,0.565,1,4,0.250,0,3,0.000,2,5,7,4,0,0,1,0,27,-8,1
36,22022,2544,0022200131,"NOV 04, 2022",LAL vs. UTA,L,34,7,19,0.368,0,5,0.000,3,5,0.600,2,8,10,8,0,1,3,3,17,-11,1
37,22022,2544,0022200117,"NOV 02, 2022",LAL vs. NOP,W,40,9,23,0.391,0,7,0.000,2,4,0.500,0,10,10,8,0,2,2,3,20,5,1
38,22022,2544,0022200095,"OCT 30, 2022",LAL vs. DEN,W,35,10,22,0.455,2,5,0.400,4,5,0.800,0,6,6,8,1,0,3,1,26,-1,1
39,22022,2544,0022200076,"OCT 28, 2022",LAL @ MIN,L,37,10,24,0.417,1,6,0.167,7,8,0.875,3,4,7,5,4,0,3,2,28,-13,1
40,22022,2544,0022200064,"OCT 26, 2022",LAL @ DEN,L,35,8,21,0.381,2,8,0.250,1,2,0.500,2,5,7,9,1,0,8,1,19,-7,1
41,22022,2544,0022200037,"OCT 23, 2022",LAL vs. POR,L,38,12,22,0.545,2,9,0.222,5,7,0.714,1,7,8,8,2,2,4,3,31,2,1
42,22022,2544,0022200016,"OCT 20, 2022",LAL vs. LAC,L,37,7,17,0.412,2,8,0.250,4,6,0.667,2,8,10,6,1,2,2,3,20,-1,1
43,22022,2544,0022200002,"OCT 18, 2022",LAL @ GSW,L,35,12,26,0.462,3,10,0.300,4,4,1.000,5,10,15,8,0,0,5,2,31,-10,1

In [5]:
pbp2_deni = playbyplayv2.PlayByPlayV2(game_id='0022200787')
df_pbp2_deni = pbp2_deni.get_data_frames()[0]
df_pbp2_deni.head(20)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022200787,2,12,0,1,7:12 PM,12:00,None,Start of 1st Period (7:12 PM EST),None,None,None,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,0
1,0022200787,4,10,0,1,7:12 PM,12:00,Jump Ball Porzingis vs. Eubanks: Tip to Morris,None,None,None,None,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,5,1629234,Drew Eubanks,1.610613e+09,Portland,Trail Blazers,POR,4,1628420,Monte Morris,1.610613e+09,Washington,Wizards,WAS,1
2,0022200787,7,2,78,1,7:12 PM,11:45,MISS Beal 8' Floating Jump Shot,None,None,None,None,4,203078,Bradley Beal,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
3,0022200787,8,4,0,1,7:12 PM,11:40,Beal REBOUND (Off:1 Def:0),None,None,None,None,4,203078,Bradley Beal,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
4,0022200787,9,1,97,1,7:12 PM,11:40,Beal Tip Layup Shot (2 PTS),None,None,0 - 2,2,4,203078,Bradley Beal,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
5,0022200787,10,2,83,1,7:12 PM,11:28,None,None,MISS Lillard 10' Fadeaway Bank Shot,None,None,5,203081,Damian Lillard,1.610613e+09,Portland,Trail Blazers,POR,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
6,0022200787,11,4,0,1,7:12 PM,11:26,Kuzma REBOUND (Off:0 Def:1),None,None,None,None,4,1628398,Kyle Kuzma,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
7,0022200787,12,6,2,1,7:12 PM,11:17,None,None,Eubanks S.FOUL (P1.T1) (N.Green),None,None,5,1629234,Drew Eubanks,1.610613e+09,Portland,Trail Blazers,POR,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,1,0,None,NaN,None,None,None,1
8,0022200787,14,3,11,1,7:13 PM,11:17,Porzingis Free Throw 1 of 2 (1 PTS),None,None,0 - 3,3,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
9,0022200787,15,3,12,1,7:13 PM,11:17,Porzingis Free Throw 2 of 2 (2 PTS),None,None,0 - 4,4,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
10,0022200787,16,2,63,1,7:13 PM,11:06,None,None,MISS Lillard 18' Fadeaway Jumper,None,None,5,203081,Damian Lillard,1.610613e+09,Portland,Trail Blazers,POR,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
11,0022200787,17,4,0,1,7:13 PM,11:03,Kuzma REBOUND (Off:0 Def:2),None,None,None,None,4,1628398,Kyle Kuzma,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
12,0022200787,18,1,108,1,7:14 PM,10:53,Gafford 1' Cutting Dunk Shot (2 PTS) (Kuzma 1 ...,None,None,0 - 6,6,4,1629655,Daniel Gafford,1.610613e+09,Washington,Wizards,WAS,4,1628398,Kyle Kuzma,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,1
13,0022200787,20,1,63,1,7:14 PM,10:35,None,None,Hart 17' Fadeaway Jumper (2 PTS) (Simons 1 AST),2 - 6,4,5,1628404,Josh Hart,1.610613e+09,Portland,Trail Blazers,POR,5,1629014,Anfernee Simons,1.610613e+09,Portland,Trail Blazers,POR,0,0,None,NaN,None,None,None,1
14,0022200787,22,1,47,1,7:14 PM,10:14,Porzingis 9' Turnaround Jump Shot (4 PTS),None,None,2 - 8,6,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
15,0022200787,23,2,1,1,7:14 PM,9:54,None,None,MISS Hart 3PT Jump Shot,None,None,5,1628404,Josh Hart,1.610613e+09,Portland,Trail Blazers,POR,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
16,0022200787,24,4,0,1,7:15 PM,9:51,Kuzma REBOUND (Off:0 Def:3),None,None,None,None,4,1628398,Kyle Kuzma,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
17,0022200787,25,6,2,1,7:15 PM,9:38,None,None,Grant S.FOUL (P1.T2) (B.Forte),None,None,5,203924,Jerami Grant,1.610613e+09,Portland,Trail Blazers,POR,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,1,0,None,NaN,None,None,None,1
18,0022200787,27,3,11,1,7:15 PM,9:38,Porzingis Free Throw 1 of 2 (5 PTS),None,None,2 - 9,7,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1
19,0022200787,28,3,12,1,7:15 PM,9:38,Porzingis Free Throw 2 of 2 (6 PTS),None,None,2 - 10,8,4,204001,Kristaps Porzingis,1.610613e+09,Washington,Wizards,WAS,0,0,None,NaN,None,None,None,0,0,None,NaN,None,None,None,1

In [6]:
WSH = teams.get_teams()
WSH

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [7]:
FranchiseLeaders(team_id=1610612747).get_data_frames()[0]

,TEAM_ID,PTS,PTS_PERSON_ID,PTS_PLAYER,AST,AST_PERSON_ID,AST_PLAYER,REB,REB_PERSON_ID,REB_PLAYER,BLK,BLK_PERSON_ID,BLK_PLAYER,STL,STL_PERSON_ID,STL_PLAYER
0,1610612747,33643,977,Kobe Bryant,10141,77142,Magic Johnson,11463,76127,Elgin Baylor,2694,76003,Kareem Abdul-Jabbar,1944,977,Kobe Bryant

In [8]:
CommonPlayerInfo(player_id=deni_id).get_data_frames()[0]

,PERSON_ID,FIRST_NAME,LAST_NAME,DISPLAY_FIRST_LAST,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FI_LAST,PLAYER_SLUG,BIRTHDATE,SCHOOL,COUNTRY,LAST_AFFILIATION,HEIGHT,WEIGHT,SEASON_EXP,JERSEY,POSITION,ROSTERSTATUS,GAMES_PLAYED_CURRENT_SEASON_FLAG,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,TEAM_CITY,PLAYERCODE,FROM_YEAR,TO_YEAR,DLEAGUE_FLAG,NBA_FLAG,GAMES_PLAYED_FLAG,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,GREATEST_75_FLAG
0,2544,LeBron,James,LeBron James,"James, LeBron",L. James,lebron-james,1984-12-30T00:00:00,St. Vincent-St. Mary HS (OH),USA,St. Vincent-St. Mary HS (OH)/USA,6-9,250,19,6,Forward,Active,Y,1610612747,Lakers,LAL,lakers,Los Angeles,lebron_james,2003,2022,N,Y,Y,2003,1,1,Y

In [9]:
alltimeleadersgrids.AllTimeLeadersGrids().get_data_frames()[0]

   PLAYER_ID          PLAYER_NAME    GP  GP_RANK IS_ACTIVE_FLAG
0        305        Robert Parish  1611        1              N
1      76003  Kareem Abdul-Jabbar  1560        2              N
2       1713         Vince Carter  1541        3              N
3       1717        Dirk Nowitzki  1522        4              N
4        304        John Stockton  1504        5              N
5        252          Karl Malone  1476        6              N
6        708        Kevin Garnett  1462        7              N
7        788         Kevin Willis  1424        8              N
8       1891          Jason Terry  1410        9              N
9       2544         LeBron James  1410        9              Y

In [10]:
from nba_api.live.nba.endpoints import scoreboard 

# Today's Score Board
Today_score = scoreboard.ScoreBoard().games.get_dict()
Today_score_df = pd.DataFrame(Today_score)
Today_score_df["homeTeam"][0]

{'teamId': 1610612739,
 'teamName': 'Cavaliers',
 'teamCity': 'Cleveland',
 'teamTricode': 'CLE',
 'wins': 35,
 'losses': 22,
 'score': 113,
 'seed': None,
 'inBonus': None,
 'timeoutsRemaining': 1,
 'periods': [{'period': 1, 'periodType': 'REGULAR', 'score': 32},
  {'period': 2, 'periodType': 'REGULAR', 'score': 19},
  {'period': 3, 'periodType': 'REGULAR', 'score': 25},
  {'period': 4, 'periodType': 'REGULAR', 'score': 37}]}

In [11]:
from nba_api.stats.endpoints import playerawards
playerawards.PlayerAwards(player_id=2544).get_data_frames()[0]

,PERSON_ID,FIRST_NAME,LAST_NAME,TEAM,DESCRIPTION,ALL_NBA_TEAM_NUMBER,SEASON,MONTH,WEEK,CONFERENCE,TYPE,SUBTYPE1,SUBTYPE2,SUBTYPE3
0,2544,LeBron,James,Cleveland Cavaliers,All-Defensive Team,1,2008-09,None,None,1610612739,Award,Kia Motors,KIADT,None
1,2544,LeBron,James,Cleveland Cavaliers,All-Defensive Team,1,2009-10,None,None,1610612739,Award,Kia Motors,KIADT,None
2,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2010-11,None,None,1610612748,Award,Kia Motors,KIADT,None
3,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2011-12,None,None,1610612748,Award,Kia Motors,KIADT,None
4,2544,LeBron,James,Miami Heat,All-Defensive Team,1,2012-13,None,None,1610612748,Award,Kia Motors,KIADT,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,2544,LeBron,James,USA,Olympic Bronze Medal,None,2004,None,None,None,Award,Olympic,Bronze,None
147,2544,LeBron,James,USA,Olympic Gold Medal,None,2008,None,None,None,Award,Olympic,Gold,None
148,2544,LeBron,James,USA,Olympic Gold Medal,None,2012,None,None,None,Award,Olympic,Gold,None
149,2544,LeBron,James,Los Angeles Lakers,NBA Player of the Week,None,2021-22,None,2021-12-06T00:00:00,West,Award,Kia Motors,KIPWK,None
150,2544,LeBron,James,Los Angeles Lakers,All-NBA,3,2021-22,None,None,West,Award,Kia Motors,KIANT,None

In [12]:
games = scoreboard.ScoreBoard()

# json
games.get_json()

'{"meta": {"version": 1, "request": "https://nba-prod-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/scoreboard/todaysScoreboard_00.json", "time": "2023-02-09 10:57:27.5727", "code": 200}, "scoreboard": {"gameDate": "2023-02-08", "leagueId": "00", "leagueName": "National Basketball Association", "games": [{"gameId": "0022200822", "gameCode": "20230208/DETCLE", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T00:00:00Z", "gameEt": "2023-02-08T19:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612739, "teamName": "Cavaliers", "teamCity": "Cleveland", "teamTricode": "CLE", "wins": 35, "losses": 22, "score": 113, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 32}, {"period": 2, "periodType": "REGULAR", "score": 19}, {"period": 3, "periodType": "REGULAR", "score": 25}, {"period": 4, "periodType": "REGULAR", "score": 37}]}, "awayTeam": {"teamId": 1610612765, "teamName": "Pistons", "teamCity": "Detroit", "teamTricode": "DET", "wins": 14, "losses": 42, "score": 85, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 14}, {"period": 2, "periodType": "REGULAR", "score": 26}, {"period": 3, "periodType": "REGULAR", "score": 28}, {"period": 4, "periodType": "REGULAR", "score": 17}]}, "gameLeaders": {"homeLeaders": {"personId": 1628386, "name": "Jarrett Allen", "jerseyNum": "31", "position": "C", "teamTricode": "CLE", "playerSlug": null, "points": 20, "rebounds": 16, "assists": 1}, "awayLeaders": {"personId": 1631105, "name": "Jalen Duren", "jerseyNum": "0", "position": "C", "teamTricode": "DET", "playerSlug": null, "points": 14, "rebounds": 9, "assists": 2}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200823", "gameCode": "20230208/CHAWAS", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T00:00:00Z", "gameEt": "2023-02-08T19:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612764, "teamName": "Wizards", "teamCity": "Washington", "teamTricode": "WAS", "wins": 25, "losses": 29, "score": 118, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 32}, {"period": 2, "periodType": "REGULAR", "score": 29}, {"period": 3, "periodType": "REGULAR", "score": 27}, {"period": 4, "periodType": "REGULAR", "score": 30}]}, "awayTeam": {"teamId": 1610612766, "teamName": "Hornets", "teamCity": "Charlotte", "teamTricode": "CHA", "wins": 15, "losses": 41, "score": 104, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 31}, {"period": 2, "periodType": "REGULAR", "score": 30}, {"period": 3, "periodType": "REGULAR", "score": 15}, {"period": 4, "periodType": "REGULAR", "score": 28}]}, "gameLeaders": {"homeLeaders": {"personId": 204001, "name": "Kristaps Porzingis", "jerseyNum": "6", "position": "F-C", "teamTricode": "WAS", "playerSlug": null, "points": 36, "rebounds": 9, "assists": 2}, "awayLeaders": {"personId": 1626179, "name": "Terry Rozier", "jerseyNum": "3", "position": "G", "teamTricode": "CHA", "playerSlug": null, "points": 19, "rebounds": 7, "assists": 6}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200824", "gameCode": "20230208/PHIBOS", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T00:30:00Z", "gameEt": "2023-02-08T19:30:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612738, "teamName": "Celtics", "teamCity": "Boston", "teamTricode": "BOS", "wins": 39, "losses": 16, "score": 106, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 30}, {"period": 2, "periodType": "REGULAR", "score": 29}, {"period": 3, "periodType": "REGULAR", "score": 27}, {"period": 4, "periodType": "REGULAR", "score": 20}]}, "awayTeam": {"teamId": 1610612755, "teamName": "76ers", "teamCity": "Philadelphia", "teamTricode": "PHI", "wins": 34, "losses": 19, "score": 99, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 27}, {"period": 2, "periodType": "REGULAR", "score": 28}, {"period": 3, "periodType": "REGULAR", "score": 24}, {"period": 4, "periodType": "REGULAR", "score": 20}]}, "gameLeaders": {"homeLeaders": {"personId": 1628369, "name": "Jayson Tatum", "jerseyNum": "0", "position": "F-G", "teamTricode": "BOS", "playerSlug": null, "points": 12, "rebounds": 8, "assists": 9}, "awayLeaders": {"personId": 201935, "name": "James Harden", "jerseyNum": "1", "position": "G", "teamTricode": "PHI", "playerSlug": null, "points": 26, "rebounds": 3, "assists": 11}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200825", "gameCode": "20230208/INDMIA", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T00:30:00Z", "gameEt": "2023-02-08T19:30:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612748, "teamName": "Heat", "teamCity": "Miami", "teamTricode": "MIA", "wins": 30, "losses": 25, "score": 116, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 39}, {"period": 2, "periodType": "REGULAR", "score": 21}, {"period": 3, "periodType": "REGULAR", "score": 29}, {"period": 4, "periodType": "REGULAR", "score": 27}]}, "awayTeam": {"teamId": 1610612754, "teamName": "Pacers", "teamCity": "Indiana", "teamTricode": "IND", "wins": 25, "losses": 31, "score": 111, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 30}, {"period": 2, "periodType": "REGULAR", "score": 33}, {"period": 3, "periodType": "REGULAR", "score": 20}, {"period": 4, "periodType": "REGULAR", "score": 28}]}, "gameLeaders": {"homeLeaders": {"personId": 1628389, "name": "Bam Adebayo", "jerseyNum": "13", "position": "C-F", "teamTricode": "MIA", "playerSlug": null, "points": 38, "rebounds": 9, "assists": 3}, "awayLeaders": {"personId": 1627741, "name": "Buddy Hield", "jerseyNum": "24", "position": "G", "teamTricode": "IND", "playerSlug": null, "points": 29, "rebounds": 7, "assists": 2}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200826", "gameCode": "20230208/SASTOR", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T00:30:00Z", "gameEt": "2023-02-08T19:30:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612761, "teamName": "Raptors", "teamCity": "Toronto", "teamTricode": "TOR", "wins": 26, "losses": 30, "score": 112, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 34}, {"period": 2, "periodType": "REGULAR", "score": 23}, {"period": 3, "periodType": "REGULAR", "score": 31}, {"period": 4, "periodType": "REGULAR", "score": 24}]}, "awayTeam": {"teamId": 1610612759, "teamName": "Spurs", "teamCity": "San Antonio", "teamTricode": "SAS", "wins": 14, "losses": 41, "score": 98, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 24}, {"period": 2, "periodType": "REGULAR", "score": 30}, {"period": 3, "periodType": "REGULAR", "score": 21}, {"period": 4, "periodType": "REGULAR", "score": 23}]}, "gameLeaders": {"homeLeaders": {"personId": 1627783, "name": "Pascal Siakam", "jerseyNum": "43", "position": "F", "teamTricode": "TOR", "playerSlug": null, "points": 37, "rebounds": 10, "assists": 7}, "awayLeaders": {"personId": 1629640, "name": "Keldon Johnson", "jerseyNum": "3", "position": "F-G", "teamTricode": "SAS", "playerSlug": null, "points": 22, "rebounds": 7, "assists": 3}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200827", "gameCode": "20230208/SACHOU", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T01:00:00Z", "gameEt": "2023-02-08T20:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612745, "teamName": "Rockets", "teamCity": "Houston", "teamTricode": "HOU", "wins": 13, "losses": 42, "score": 128, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 37}, {"period": 2, "periodType": "REGULAR", "score": 25}, {"period": 3, "periodType": "REGULAR", "score": 35}, {"period": 4, "periodType": "REGULAR", "score": 31}]}, "awayTeam": {"teamId": 1610612758, "teamName": "Kings", "teamCity": "Sacramento", "teamTricode": "SAC", "wins": 31, "losses": 23, "score": 130, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 30}, {"period": 2, "periodType": "REGULAR", "score": 28}, {"period": 3, "periodType": "REGULAR", "score": 41}, {"period": 4, "periodType": "REGULAR", "score": 31}]}, "gameLeaders": {"homeLeaders": {"personId": 1630224, "name": "Jalen Green", "jerseyNum": "4", "position": "G", "teamTricode": "HOU", "playerSlug": null, "points": 41, "rebounds": 2, "assists": 2}, "awayLeaders": {"personId": 1628368, "name": "De\'Aaron Fox", "jerseyNum": "5", "position": "G", "teamTricode": "SAC", "playerSlug": null, "points": 31, "rebounds": 5, "assists": 11}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200828", "gameCode": "20230208/MINUTA", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T02:00:00Z", "gameEt": "2023-02-08T21:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612762, "teamName": "Jazz", "teamCity": "Utah", "teamTricode": "UTA", "wins": 27, "losses": 29, "score": 118, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 31}, {"period": 2, "periodType": "REGULAR", "score": 36}, {"period": 3, "periodType": "REGULAR", "score": 21}, {"period": 4, "periodType": "REGULAR", "score": 30}]}, "awayTeam": {"teamId": 1610612750, "teamName": "Timberwolves", "teamCity": "Minnesota", "teamTricode": "MIN", "wins": 30, "losses": 28, "score": 143, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 33}, {"period": 2, "periodType": "REGULAR", "score": 44}, {"period": 3, "periodType": "REGULAR", "score": 40}, {"period": 4, "periodType": "REGULAR", "score": 26}]}, "gameLeaders": {"homeLeaders": {"personId": 1629012, "name": "Collin Sexton", "jerseyNum": "2", "position": "G", "teamTricode": "UTA", "playerSlug": null, "points": 22, "rebounds": 5, "assists": 5}, "awayLeaders": {"personId": 1630162, "name": "Anthony Edwards", "jerseyNum": "1", "position": "G", "teamTricode": "MIN", "playerSlug": null, "points": 31, "rebounds": 7, "assists": 8}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200829", "gameCode": "20230208/DALLAC", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T03:00:00Z", "gameEt": "2023-02-08T22:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612746, "teamName": "Clippers", "teamCity": "LA", "teamTricode": "LAC", "wins": 31, "losses": 27, "score": 104, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 25}, {"period": 2, "periodType": "REGULAR", "score": 27}, {"period": 3, "periodType": "REGULAR", "score": 26}, {"period": 4, "periodType": "REGULAR", "score": 26}]}, "awayTeam": {"teamId": 1610612742, "teamName": "Mavericks", "teamCity": "Dallas", "teamTricode": "DAL", "wins": 30, "losses": 26, "score": 110, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 41}, {"period": 2, "periodType": "REGULAR", "score": 19}, {"period": 3, "periodType": "REGULAR", "score": 21}, {"period": 4, "periodType": "REGULAR", "score": 29}]}, "gameLeaders": {"homeLeaders": {"personId": 1626181, "name": "Norman Powell", "jerseyNum": "24", "position": "G", "teamTricode": "LAC", "playerSlug": null, "points": 24, "rebounds": 7, "assists": 1}, "awayLeaders": {"personId": 202681, "name": "Kyrie Irving", "jerseyNum": "11", "position": "G", "teamTricode": "DAL", "playerSlug": null, "points": 24, "rebounds": 4, "assists": 5}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022200830", "gameCode": "20230208/GSWPOR", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2023-02-09T03:00:00Z", "gameEt": "2023-02-08T22:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "seriesText": "", "homeTeam": {"teamId": 1610612757, "teamName": "Trail Blazers", "teamCity": "Portland", "teamTricode": "POR", "wins": 27, "losses": 28, "score": 125, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 34}, {"period": 2, "periodType": "REGULAR", "score": 29}, {"period": 3, "periodType": "REGULAR", "score": 32}, {"period": 4, "periodType": "REGULAR", "score": 30}]}, "awayTeam": {"teamId": 1610612744, "teamName": "Warriors", "teamCity": "Golden State", "teamTricode": "GSW", "wins": 28, "losses": 27, "score": 122, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 27}, {"period": 2, "periodType": "REGULAR", "score": 40}, {"period": 3, "periodType": "REGULAR", "score": 28}, {"period": 4, "periodType": "REGULAR", "score": 27}]}, "gameLeaders": {"homeLeaders": {"personId": 203081, "name": "Damian Lillard", "jerseyNum": "0", "position": "G", "teamTricode": "POR", "playerSlug": null, "points": 33, "rebounds": 10, "assists": 11}, "awayLeaders": {"personId": 1629673, "name": "Jordan Poole", "jerseyNum": "3", "position": "G", "teamTricode": "GSW", "playerSlug": null, "points": 38, "rebounds": 1, "assists": 7}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}]}}'

In [26]:
from nba_api.stats.endpoints import BoxScoreAdvancedV2, BoxScorePlayerTrackV2, CumeStatsPlayer

In [19]:
box1 = BoxScoreAdvancedV2(game_id='0022101217').get_data_frames()[0]
box1.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0022101217,1610612764,WAS,Washington,1630166,Deni Avdija,Deni,F,,31:08,110.8,107.8,117.7,123.1,-6.9,-15.3,0.174,4.0,23.5,0.031,0.129,0.079,5.9,0.458,0.482,0.183,0.188,100.40,99.44,82.87,64,0.079
1,0022101217,1610612764,WAS,Washington,1629060,Rui Hachimura,Rui,F,,32:20,113.2,111.6,113.2,119.7,-0.1,-8.1,0.091,0.0,9.1,0.061,0.074,0.067,0.0,0.500,0.528,0.260,0.270,102.28,100.21,83.51,69,0.103
2,0022101217,1610612764,WAS,Washington,1629655,Daniel Gafford,Daniel,C,,27:58,122.6,119.0,113.6,120.7,9.0,-1.7,0.042,1.0,6.3,0.107,0.160,0.132,6.3,0.444,0.485,0.231,0.237,101.19,99.55,82.96,58,0.040
3,0022101217,1610612764,WAS,Washington,1630557,Corey Kispert,Corey,G,,25:37,123.9,123.5,121.5,128.3,2.4,-4.8,0.053,0.0,7.7,0.000,0.136,0.060,0.0,0.833,0.833,0.200,0.201,100.06,97.44,81.20,51,0.154
4,0022101217,1610612764,WAS,Washington,203107,Tomas Satoransky,Tomas,G,,20:16,121.9,118.6,93.8,97.7,28.1,20.9,0.474,9.0,69.2,0.091,0.182,0.136,7.7,0.833,0.833,0.080,0.084,102.55,101.84,84.87,43,0.174

In [24]:
box2 = BoxScorePlayerTrackV2(game_id='0022101217')
box2

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [32]:
box3 = CumeStatsPlayer(player_id='1630166', game_ids='0022101217').get_data_frames()[0]
for i in box3.columns:
    for j in

Index(['DATE_EST', 'VISITOR_TEAM', 'HOME_TEAM', 'GP', 'GS', 'ACTUAL_MINUTES',
       'ACTUAL_SECONDS', 'FG', 'FGA', 'FG_PCT', 'FG3', 'FG3A', 'FG3_PCT', 'FT',
       'FTA', 'FT_PCT', 'OFF_REB', 'DEF_REB', 'TOT_REB', 'AVG_TOT_REB', 'AST',
       'PF', 'DQ', 'STL', 'TURNOVERS', 'BLK', 'PTS', 'AVG_PTS'],
      dtype='object')

In [ ]:
df_league_standings = LeagueStandingsV3(season_type='Regular Season').get_data_frames()[0]
df_league_standings.head()

check_data_quality(df_league_standings) 

df_league_standings = df_league_standings.dropna(axis='columns')
df_league_standings.columns

df_stats_all_year_preprocess.columns

df_league_standings = df_league_standings.rename(columns=lambda x: x + '_team')
merged_df = df_stats_all_year_preprocess.merge(df_league_standings, left_on='TEAM_ID', right_on='TeamID_team')
merged_df